# Generated by Django 4.2 on 2023-05-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_alter_product_description_alter_product_pimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Oname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('items', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('poheno', models.IntegerField()),
                ('delivery', models.CharField(max_length=100)),
            ],
        ),
    ]
