# Generated by Django 4.2 on 2023-05-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
